import type { Teacher, Parent, TutoringRequest, Review } from "./types"

export const mockTeachers: Teacher[] = [
  {
    id: "teacher-1",
    email: "sarah@example.com",
    name: "Sarah Johnson",
    role: "teacher",
    bio: "Experienced Math tutor with 8 years of teaching experience. Specializing in algebra, geometry, and calculus.",
    subjects: ["Mathematics", "Algebra", "Geometry", "Calculus"],
    qualifications: ["B.S. Mathematics", "Teaching Certification"],
    hourlyRate: 45,
    location: "San Francisco, CA",
    latitude: 37.7749,
    longitude: -122.4194,
    verified: true,
    rating: 4.8,
    reviewCount: 24,
    availability: ["Monday", "Wednesday", "Friday", "Saturday"],
    experience: 8,
    image: "/professional-teacher-woman.jpg",
    avatar: "/teacher-avatar.png",
    createdAt: new Date("2022-01-15"),
  },
  {
    id: "teacher-2",
    email: "james@example.com",
    name: "James Chen",
    role: "teacher",
    bio: "English and Literature specialist. Help students improve writing, reading comprehension, and exam preparation.",
    subjects: ["English", "Literature", "Writing", "SAT Prep"],
    qualifications: ["M.A. English Literature", "TESOL Certification"],
    hourlyRate: 40,
    location: "San Francisco, CA",
    latitude: 37.7849,
    longitude: -122.4094,
    verified: true,
    rating: 4.9,
    reviewCount: 31,
    availability: ["Tuesday", "Thursday", "Saturday", "Sunday"],
    experience: 6,
    image: "/professional-teacher-man.jpg",
    avatar: "/teacher-avatar.png",
    createdAt: new Date("2022-06-20"),
  },
  {
    id: "teacher-3",
    email: "priya@example.com",
    name: "Priya Patel",
    role: "teacher",
    bio: "Science tutor passionate about making complex concepts easy to understand. Physics, Chemistry, and Biology.",
    subjects: ["Physics", "Chemistry", "Biology", "Science"],
    qualifications: ["B.S. Biology", "B.S. Chemistry", "Teaching Certification"],
    hourlyRate: 50,
    location: "San Francisco, CA",
    latitude: 37.7649,
    longitude: -122.4294,
    verified: true,
    rating: 4.7,
    reviewCount: 18,
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    experience: 7,
    image: "/professional-teacher-woman-science.jpg",
    avatar: "/teacher-avatar.png",
    createdAt: new Date("2021-09-10"),
  },
  {
    id: "teacher-4",
    email: "michael@example.com",
    name: "Michael Rodriguez",
    role: "teacher",
    bio: "Spanish language tutor with native fluency. Conversational Spanish, grammar, and cultural immersion.",
    subjects: ["Spanish", "Languages", "Conversational Spanish"],
    qualifications: ["Native Spanish Speaker", "Language Teaching Certification"],
    hourlyRate: 35,
    location: "San Francisco, CA",
    latitude: 37.7549,
    longitude: -122.4394,
    verified: true,
    rating: 4.6,
    reviewCount: 15,
    availability: ["Monday", "Wednesday", "Friday", "Saturday", "Sunday"],
    experience: 5,
    image: "/professional-teacher-man-spanish.jpg",
    avatar: "/teacher-avatar.png",
    createdAt: new Date("2023-02-14"),
  },
  {
    id: "teacher-5",
    email: "emma@example.com",
    name: "Emma Wilson",
    role: "teacher",
    bio: "Computer Science and Programming tutor. Python, JavaScript, Web Development, and Data Structures.",
    subjects: ["Computer Science", "Programming", "Python", "JavaScript", "Web Development"],
    qualifications: ["B.S. Computer Science", "Full Stack Developer"],
    hourlyRate: 55,
    location: "San Francisco, CA",
    latitude: 37.7849,
    longitude: -122.3994,
    verified: true,
    rating: 4.9,
    reviewCount: 28,
    availability: ["Tuesday", "Thursday", "Saturday", "Sunday"],
    experience: 9,
    image: "/professional-teacher-woman-tech.jpg",
    avatar: "/teacher-avatar.png",
    createdAt: new Date("2021-05-22"),
  },
]

export const mockParents: Parent[] = [
  {
    id: "parent-1",
    email: "parent@example.com",
    name: "Alice Thompson",
    role: "parent",
    location: "San Francisco, CA",
    latitude: 37.7749,
    longitude: -122.4194,
    avatar: "/parent-avatar.png",
    createdAt: new Date("2023-01-10"),
  },
]

export const mockRequests: TutoringRequest[] = [
  {
    id: "request-1",
    parentId: "parent-1",
    teacherId: "teacher-1",
    subject: "Mathematics",
    level: "High School",
    description: "Need help with algebra and geometry for upcoming exams",
    status: "accepted",
    proposedDate: new Date("2025-11-01"),
    location: "San Francisco, CA",
    isOnline: false,
    createdAt: new Date("2025-10-20"),
  },
]

export const mockReviews: Review[] = [
  {
    id: "review-1",
    requestId: "request-1",
    parentId: "parent-1",
    teacherId: "teacher-1",
    rating: 5,
    comment: "Sarah is an excellent tutor! Very patient and explains concepts clearly.",
    createdAt: new Date("2025-10-25"),
  },
]
